name: Production deployment

on: 
  push:
    branches:
      - master

env:
  AZURE_RESOURCE_GROUP: tim-reslv-cd-with-actions
  AZURE_APP_PLAN: tim-reslv-actions-ttt-deployment
  AZURE_LOCATION: '"East Asia"'
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: tim-reslv-ttt-app
  #################################################